// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd4KaIaFzLDcT1VleIvSTBHsdyymVdO0k',
    appId: '1:134700258097:web:4b6cbe9f0c32e261109610',
    messagingSenderId: '134700258097',
    projectId: 'm-tracker-62124',
    authDomain: 'm-tracker-62124.firebaseapp.com',
    storageBucket: 'm-tracker-62124.appspot.com',
    measurementId: 'G-GX79LQ035J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA158G9xK60m4kayzLRmQL5FWgmdiuJg0Q',
    appId: '1:134700258097:android:cce4790309f78af3109610',
    messagingSenderId: '134700258097',
    projectId: 'm-tracker-62124',
    storageBucket: 'm-tracker-62124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfBJg-FRJ26ZUjlb1IIVweNQGN4FE_z2M',
    appId: '1:134700258097:ios:b6358ffe1a7c61bf109610',
    messagingSenderId: '134700258097',
    projectId: 'm-tracker-62124',
    storageBucket: 'm-tracker-62124.appspot.com',
    iosClientId: '134700258097-ribaghhmks0soi0u079mgka3qj3kl565.apps.googleusercontent.com',
    iosBundleId: 'com.example.new1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfBJg-FRJ26ZUjlb1IIVweNQGN4FE_z2M',
    appId: '1:134700258097:ios:b6358ffe1a7c61bf109610',
    messagingSenderId: '134700258097',
    projectId: 'm-tracker-62124',
    storageBucket: 'm-tracker-62124.appspot.com',
    iosClientId: '134700258097-ribaghhmks0soi0u079mgka3qj3kl565.apps.googleusercontent.com',
    iosBundleId: 'com.example.new1',
  );
}
